import { Dimensions, StyleSheet } from "react-native";
const { width, height, scale } = Dimensions.get("window");
export const backButtonSize = scale * 12;
const styles = StyleSheet.create({
  containerHome: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9F9FB",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9F9FB",
  },
  containerQoute: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9F9FB",
  },
  productImage: {
    width: width/1.5,
    height: height/3,
    marginHorizontal: scale * 5,
    borderRadius: scale * 10,
    margin: scale * 6,
    alignSelf: "center",
  },
  logo: {
    width: width / 2,
    height: height / 4,
    marginBottom: scale * 20,
  },
  button: {
    flexDirection: "row",
    width: 250,
    height: 55,
    margin: scale * 10,
    backgroundColor: "red",
    borderRadius: 28,
    shadowColor: "red",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  disbutton: {
    flexDirection: "row",
    width: 250,
    height: 55,
    margin: scale * 10,
    backgroundColor: "brown",
    borderRadius: 28,
    shadowColor: "brown",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonSubmit: {
    width: width / 1.6,
    height: height / 14,
    margin: scale * 10,
    backgroundColor: "red",
    borderRadius: 25,
    shadowColor: "red",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    justifyContent: "center",
    alignSelf: "center",
  },
  buttonMoreDetails: {
    width: width / 2,
    height: height / 14,
    margin: scale * 4,
    backgroundColor: "red",
    borderRadius: 25,
    shadowColor: "red",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    justifyContent: "center",
    justifyContent: "space-evenly",
    flexDirection: "row",
    alignItems: "center",
  },
  textInput: {
    width: width / 1.1,
    padding: scale * 5,
    height: height / 14,
    margin: scale * 4,
    backgroundColor: "#F0F0F0",
    borderRadius: 16,
    justifyContent: "center",
  },
  headerTitle: { color: "red", fontSize: 18,fontFamily:'RB' },
  buttontext: {
    fontSize: 14,
    color: "white",
    alignSelf: "center", 
    fontFamily:'RM'
  },
  checkBoxFill: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "red",
    margin: 6,
    borderRadius: 8,
  },
  checkBox: {
    width: 25,
    height: 25,
    borderWidth: 2,
    borderColor: "#E0E0E0",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    margin: 6,
    borderRadius: 8,
  },
  
  buttontextSubmit: {
    fontSize: 16,
    color: "#fff",
    alignSelf: "center",
    fontFamily:'RB'
  },
  BSW: {
    alignSelf: "center",
    color: "red",
    fontSize: 20,

    marginBottom: scale * 5,
    fontFamily:'RB'
  },
  image: {
    flex: 1,
    width: width / 2,
    height: height / 3,
    borderRadius: scale * 6,
  },
  picker: { backgroundColor: "#fff", width: width / 1.2, alignSelf: "center",fontFamily:'RM' },
  description: {
    textAlign: "justify",
    padding: scale * 2,
    margin: scale * 5,
    fontSize: 14,
    alignSelf: "center",
    fontFamily:'RR'
  },
  collecttodayButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    margin: scale * 5,
    backgroundColor: "#E5040A",
    borderRadius: 25,
    shadowColor: "#E5040A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    width: width / 2,
    height: height / 14,
    marginBottom: scale * 8,
  },
  card: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 24,
    margin: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 3,
    justifyContent:'center',
    alignItems:'center'
  },
});

export default styles;
