export const ALL_COLORS = [
  { id: "White", name: "White", hex: "#FFFFFF" },
  { id: "AnthraciteGrey", name: "Anthracite Grey", hex: "#424A51" },
  { id: "SlateGrey", name: "Slate Grey", hex: "#616A71" },
  { id: "SilverGrey", name: "Silver Grey", hex: "#A8AFAD" },
  { id: "WoodgrainWhite", name: "Woodgrain White", hex: "#F5F5DC" },
  { id: "BasaltGrey", name: "Basalt Grey", hex: "#4C5156" },
  { id: "AgateGrey", name: "Agate Grey", hex: "#B6BEB6" },
  { id: "Cream", name: "Cream", hex: "#FFFDD0" },
  { id: "Rosewood", name: "Rosewood", hex: "#4A1C14" },
  { id: "PebbleGrey", name: "Pebble Grey", hex: "#B0B6BA" },
  { id: "BeckBrown", name: "Beck Brown", hex: "#2A1813" },
  { id: "GoldenOak", name: "Golden Oak", hex: "#B47C3B" },
  { id: "ChartwellGreen", name: "Chartwell Green", hex: "#95AFA0" },
  { id: "IrishOak", name: "Irish Oak", hex: "#C79D6B" },
];

export const WINDOW_ASSETS = {
  window1: {
    White: require('../assets/window-style-images/window-1/Window1White.png'),
    // Fallbacks for window 1 will be handled in code
  },
  window2: {
    White: require('../assets/window-style-images/window-2/Window2White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-2/Window2AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-2/Window2SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-2/Window2SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-2/Window2WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-2/Window2BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-2/Window2AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-2/Window2Cream.png'),
    Rosewood: require('../assets/window-style-images/window-2/Window2Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-2/Window2PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-2/Window2BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-2/Window2GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-2/Window2ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-2/Window2IrishOak.png'),
  },
  window3: {
    White: require('../assets/window-style-images/window-3/Window3White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-3/Window3AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-3/Window3SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-3/Window3SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-3/Window3WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-3/Window3BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-3/Window3AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-3/Window3Cream.png'),
    Rosewood: require('../assets/window-style-images/window-3/Window3Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-3/Window3PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-3/Window3BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-3/Window3GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-3/Window3ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-3/Window3IrishOak.png'),
  },
  window4: {
    White: require('../assets/window-style-images/window-4/Window4White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-4/Window4AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-4/Window4SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-4/Window4SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-4/Window4WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-4/Window4BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-4/Window4AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-4/Window4Cream.png'),
    Rosewood: require('../assets/window-style-images/window-4/Window4Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-4/Window4PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-4/Window4BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-4/Window4GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-4/Window4ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-4/Window4IrishOak.png'),
  },
  window5: {
    White: require('../assets/window-style-images/window-5/Window5White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-5/Window5AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-5/Window5SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-5/Window5SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-5/Window5WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-5/Window5BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-5/Window5AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-5/Window5Cream.png'),
    Rosewood: require('../assets/window-style-images/window-5/Window5Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-5/Window5PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-5/Window5BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-5/Window5GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-5/Window5ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-5/Window5IrishOak.png'),
  },
  window6: {
    White: require('../assets/window-style-images/window-6/Window6White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-6/Window6AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-6/Window6SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-6/Window6SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-6/Window6WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-6/Window6BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-6/Window6AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-6/Window6Cream.png'),
    Rosewood: require('../assets/window-style-images/window-6/Window6Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-6/Window6PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-6/Window6BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-6/Window6GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-6/Window6ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-6/Window6IrishOak.png'),
  },
  window7: {
    White: require('../assets/window-style-images/window-7/Window7White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-7/Window7AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-7/Window7SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-7/Window7SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-7/Window7WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-7/Window7BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-7/Window7AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-7/Window7Cream.png'),
    Rosewood: require('../assets/window-style-images/window-7/Window7Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-7/Window7PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-7/Window7BeckBrown.png'),
    GoldenOak: require('../assets/window-style-images/window-7/Window7GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-7/Window7ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-7/Window7IrishOak.png'),
  },
  window8: {
    White: require('../assets/window-style-images/window-8/Window8White.png'),
    AnthraciteGrey: require('../assets/window-style-images/window-8/Window8AnthraciteGrey.png'),
    SlateGrey: require('../assets/window-style-images/window-8/Window8SlateGrey.png'),
    SilverGrey: require('../assets/window-style-images/window-8/Window8SilverGrey.png'),
    WoodgrainWhite: require('../assets/window-style-images/window-8/Window8WoodgrainWhite.png'),
    BasaltGrey: require('../assets/window-style-images/window-8/Window8BasaltGrey.png'),
    AgateGrey: require('../assets/window-style-images/window-8/Window8AgateGrey.png'),
    Cream: require('../assets/window-style-images/window-8/Window8Cream.png'),
    Rosewood: require('../assets/window-style-images/window-8/Window8Rosewood.png'),
    PebbleGrey: require('../assets/window-style-images/window-8/Window8PebbleGrey.png'),
    BeckBrown: require('../assets/window-style-images/window-8/Window8BeckBrown.png'),
    // GoldenOak: require('../assets/window-style-images/window-8/Window8GoldenOak.png'),
    ChartwellGreen: require('../assets/window-style-images/window-8/Window8ChartwellGreen.png'),
    IrishOak: require('../assets/window-style-images/window-8/Window8IrishOak.png'),
  }
};

export const WINDOW_KEYS = ["window2", "window3", "window4", "window5", "window6", "window7", "window8"];
